;;; clippy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from clippy.el

(autoload 'clippy-say "clippy" "\
Display pop-up box with Clippy saying TEXT.
The box disappears after the next input event.

If optional argument FILL is non-nil, the text is filled to 72
columns.

(fn TEXT &optional FILL)")
(autoload 'clippy-describe-function "clippy" "\
Display the full documentation of FUNCTION (a symbol) in tooltip.

(fn FUNCTION)" t)
(autoload 'clippy-describe-variable "clippy" "\
Display the full documentation of VARIABLE (a symbol) in tooltip.

(fn VARIABLE)" t)
(register-definition-prefixes "clippy" '("clippy-"))

;;; End of scraped data

(provide 'clippy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; clippy-autoloads.el ends here
