;;; enlight-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from enlight.el

(autoload 'enlight "enlight" "\
Return `enlight' buffer ready for display.")
(autoload 'enlight-open "enlight" "\
Open `enlight'." t)
(register-definition-prefixes "enlight" '("enlight-"))


;;; Generated autoloads from enlight-menu.el

(autoload 'enlight-menu "enlight-menu" "\
Generate a vertical menu using ALIST and return as a string.

The form of ALIST:

  ((\"Section-1\" ITEM ITEM ...)
   (\"Section-2\" ITEM ITEM ...)
   ...)

Where ITEM is of the form:

  (\"Item text\" SYMBOL-OR-FORM [KEY])

SYMBOL-OR-FORM is a form or a function symbol.  If it's a
function symbol, the function will be called when a user presses
RET or clicks on that item.

KEY is a string acceptable for `keymap-set'.  If it is specified,
the SYMBOL-OR-FORM is bound to this key in the dashboard buffer
keymap.

(fn ALIST)")
(register-definition-prefixes "enlight-menu" '("enlight-"))

;;; End of scraped data

(provide 'enlight-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; enlight-autoloads.el ends here
