;;; spotify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from spotify.el

 (autoload 'spotify-play "spotify" "Call Play on spotify player." t)
 (autoload 'spotify-pause "spotify" "Call Pause on spotify player." t)
 (autoload 'spotify-playpause "spotify" "Call PlayPause on spotify player." t)
 (autoload 'spotify-next "spotify" "Call Next on spotify player." t)
 (autoload 'spotify-previous "spotify" "Call Previous on spotify player." t)
 (autoload 'spotify-current "spotify" "Return the current song playing in spotify application." t)
 (autoload 'spotify-quit "spotify" "Quit the spotify application." t)
 (autoload 'spotify-enable-song-notifications "spotify" "Enable notifications for the currently playing song in spotify application." t)
 (autoload 'spotify-disable-song-notifications "spotify" "Disable notifications for the currently playing song in spotify application." t)
(register-definition-prefixes "spotify" '("spotify-"))

;;; End of scraped data

(provide 'spotify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; spotify-autoloads.el ends here
